<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Overview</name>
   <tag></tag>
   <elementGuidId>c9346560-a843-4cde-8f64-cb75f33204a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.site-header__menu-nav-item-main > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='siteHeader']/div[2]/div[2]/ul/li/div[2]/div/ul/li/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c3d3ba2-6b64-49cc-8206-f552b41a2dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>4de03786-583b-455e-94a4-ca2990ea8ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteHeader&quot;)/div[@class=&quot;wrapper site-header__wrapper&quot;]/div[@class=&quot;site-header__left&quot;]/ul[@class=&quot;site-header__nav&quot;]/li[@class=&quot;site-header__nav-item&quot;]/div[@class=&quot;site-header__menu show--&quot;]/div[@class=&quot;wrapper&quot;]/ul[@class=&quot;site-header__menu-nav&quot;]/li[@class=&quot;site-header__menu-nav-item&quot;]/a[@class=&quot;site-header__menu-nav-item-main&quot;]/div[1]</value>
      <webElementGuid>51e990cf-f44e-4471-b679-3a2bd232493e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siteHeader']/div[2]/div[2]/ul/li/div[2]/div/ul/li/a/div</value>
      <webElementGuid>c10207fa-2834-4ae2-b8a1-fdb961223841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Home'])[2]/following::div[1]</value>
      <webElementGuid>2250f6bc-9af5-42df-91e0-6f5a6e275303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[2]</value>
      <webElementGuid>f52a2f39-f431-433e-9286-bbb7a9087db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pakej MyKabel'])[1]/preceding::div[2]</value>
      <webElementGuid>efb1b5f4-04ba-4ffb-98db-7005d78c8239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gig Speed Home (FTTR)'])[1]/preceding::div[3]</value>
      <webElementGuid>f90af441-5f1e-4e66-be03-5121cd868da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Overview']/parent::*</value>
      <webElementGuid>243c089d-2c96-48a1-8ddc-e15e2c60d48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>6b0db7b0-2e7b-4d9d-832f-89c6ff7877b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Overview' or . = 'Overview')]</value>
      <webElementGuid>61f054ac-d53b-4c6b-b36a-4496d54eb851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
